### ISSUE TITLE
Can you update for more record option?

### ISSUE THREAD

**Issue by tungnb** [drittich/DnsTube#24]
We have some record for email server like this: "v=spf1 mx a ip4:XXX.XXX.XXX.XXX -all"
Can you update option for record like that?

**Comment by drittich** [comment]
I'm not familiar with SPF records, but to clarify, it looks like you create a TXT record with this as the value? I can give it a shot if you are willing to beta-test. Let me know.

**Comment by tungnb** [comment]
Yes, it is SPF and TXT too.
I hope I can try it on beta test.
Thank you so much

**Comment by drittich** [comment]
OK, stand by...

**Comment by drittich** [comment]
@tungnb Give this a try: [v0.8.0-beta3](https://github.com/drittich/DnsTube/releases/tag/v0.8.0-beta3). It's portable, so expects the config to be in the same folder as the .exe. (You can copy over the old config, the path is shown when you launch the old version you have.)

Due to a settings change you'll need to re-select the entries that you want DnsTube to update.

**Comment by tungnb** [comment]
Thank you so much.
It worked.
Autodetect IP and change it on string is very goog.
Thanks for your support
